# Generated by Django 5.2.5 on 2025-09-25 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SteamGame',
            fields=[
                ('appid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('has_details', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SteamGameDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('required_age', models.CharField(blank=True, max_length=10, null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('about_the_game', models.TextField(blank=True, null=True)),
                ('header_image', models.URLField(blank=True, max_length=500, null=True)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('developers', models.TextField(blank=True, null=True)),
                ('price_overview', models.JSONField(blank=True, null=True)),
                ('categories', models.JSONField(blank=True, null=True)),
                ('genres', models.JSONField(blank=True, null=True)),
                ('steam_game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api.steamgame')),
            ],
        ),
    ]
