# Generated by Django 5.2.5 on 2025-09-25 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SteamGameDetails',
            new_name='SteamGameDetail',
        ),
    ]
