# Generated by Django 5.2.5 on 2025-09-26 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_steamgamedetails_steamgamedetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steamgamedetail',
            name='price_overview',
        ),
    ]
