# Generated by Django 5.2.5 on 2025-09-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_steamgamedetail_price_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamgamedetail',
            name='is_game',
            field=models.BooleanField(default=True),
        ),
    ]
